title: <p align="center"> Siva Vaddadi </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/siva-vaddadi-6a373634/">LinkedIn</a> |
  <a href="https://github.com/sivavaddadi">GitHub</a>
  
  <br>   
  I'm software engineer.
  Also learning AI/ML.
  <br>
  </p>



theme: jekyll-theme-minimal
